# Generated by Django 5.1.4 on 2024-12-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=50)),
                ('main_image', models.ImageField(upload_to='puppy_images/')),
                ('description', models.TextField()),
                ('videos', models.URLField(blank=True, null=True)),
                ('additional_images', models.JSONField(default=list)),
            ],
        ),
    ]
