# Generated by Django 5.1.4 on 2024-12-09 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppy',
            name='videos',
        ),
        migrations.AddField(
            model_name='puppy',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puppy',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='puppies/videos/'),
        ),
        migrations.RemoveField(
            model_name='puppy',
            name='additional_images',
        ),
        migrations.AlterField(
            model_name='puppy',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='puppy_images/'),
        ),
        migrations.CreateModel(
            name='PuppyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='puppies/images/')),
                ('puppy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puppy_images_set', to='puppies.puppy')),
            ],
        ),
        migrations.AddField(
            model_name='puppy',
            name='additional_images',
            field=models.ManyToManyField(related_name='puppies', to='puppies.puppyimage'),
        ),
    ]
