# Generated by Django 5.1.4 on 2024-12-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppies', '0002_remove_puppy_videos_puppy_age_puppy_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='puppy',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='puppies', to='puppies.puppyimage'),
        ),
    ]
